apiVersion: v1
kind: Service
metadata:
  name: transactions-api-service
spec:
  selector:
    app: transactions-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
    - protocol: TCP
      port: 90
      targetPort: grpc-server
      name: grpc-service
  type: LoadBalancer
  # change type to ClusterIP when using ingress
  # type: ClusterIP